### ISSUE TITLE
Windows Store install not working

### ISSUE THREAD

**Issue by max-scopp** [carlelieser/glimmr-release#1]
The site https://glimmr.app/ is down. I cannot install from the windows store.

Specifically, the following URL cannot be used to download the executable:
https://glimmr.app/releases/v0.3.5/glimmr-setup.exe

Regards

**Comment by carlelieser** [comment]
Hey @max-scopp, thanks for posting this. I was able to get the site back up and running. Windows store installation and the direct download from the site should work now.
